<dec f='codebrowser/Include/pyerrors.h' l='156' type='PyObject *'/>
<def f='codebrowser/Objects/exceptions.c' l='538' macro='1' type='PyObject *'/>
<use f='codebrowser/Objects/exceptions.c' l='2513' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2585' macro='1' u='r'/>
<use f='codebrowser/Objects/genobject.c' l='389' u='r' c='gen_close'/>
<use f='codebrowser/Objects/genobject.c' l='403' u='r' c='gen_close'/>
<use f='codebrowser/Objects/genobject.c' l='425' u='r' c='_gen_throw'/>
<use f='codebrowser/Objects/genobject.c' l='1542' u='r' c='async_gen_unwrap_value'/>
<use f='codebrowser/Objects/genobject.c' l='1886' u='r' c='async_gen_athrow_send'/>
<use f='codebrowser/Objects/genobject.c' l='1951' u='r' c='async_gen_athrow_send'/>
